### ISSUE TITLE
UI Improvements

### ISSUE THREAD

**Issue by philmcmahon** [guardian/explain-maker#15]
- [x]  Split title, body blocks
- [x] Add labels to input areas
- [x] Show timestamp of when last saved
- [x] Add word count (probably just client side for now) - probably 2 warnings - too long for non-collapsible then just too long generally
- [x] Relevant links in toolbar
- [x] Add tagmanager/composer-commissioning styles
- [x] Make the default body blank (we should now be able to get away with inserting a character)

**Comment by shtukas** [comment]
> Split title, body blocks
> Add labels to input areas
> Show timestamp of when last saved

Done

> Relevant links in toolbar

Nothing else than navigation between dashboard and item editor.  Done.

**Comment by shtukas** [comment]
So the "Make the default body blank" is going to remain undone because Dynamo doesn't allow objects values to be empty strings. That being said, this was only for purity and will never be a problem because neither the title nor the body are supposed to be empty anyway.

**Comment by shtukas** [comment]
Update from my previous comment. Title and body can now be blank.
